### ISSUE TITLE
reading 'RAPL_ENERGY_CORES' fails on creating fb

### ISSUE THREAD

**Issue by derpeter** [VitorRamos/performance_features#13]
I'm not entierly sure what the problem is here. The RAPL Energy elements are listed fine by get_supported_events() but run into the error below. Not 100% sure how debug if this is resulting from the c lib below or an issue in the python part.

    raise Exception("Erro creating fd "+e_name)
Exception: Erro creating fd RAPL_ENERGY_CORES

**Comment by VitorRamos** [comment]
Can you check if works with "SYSTEMWIDE:RAPL_ENERGY_PKG"?

The RAPL_ENERGY_PKG is a global counter, it cannot be attached to a specific process, for those counters you can specify the SYSTEMWIDE at the beginning but keep in mind that the energy reported will be for the entire CPU.

There are also counters that need other special attributes, you can check these attributes with get_event_attrs function.

**Comment by derpeter** [comment]
Your are right of course. It works with Systemwide. Thanks a lot for the quick response and sorry for the noise
